# This script was generated by Taurus

from gevent import sleep
from re import findall, compile
from locust import HttpUser, TaskSet, task, constant

class UserBehaviour(TaskSet):
    @task(1)
    def generated_task(self):
        self.client.get(timeout=30.0, url="https://jsonplaceholder.typicode.com/posts/1")


class GeneratedSwarm(HttpUser):
    tasks = [UserBehaviour]
    host = ""
    wait_time = constant(0)

