jmeter.save.saveservice.autoflush=true
jmeter.save.saveservice.connect_time=true
jmeterengine.force.system.exit=true
summariser.name=
jmeterengine.nongui.port=4445
jmeterengine.nongui.maxport=4445
jmeter.save.saveservice.timestamp_format=ms
sampleresult.default.encoding=UTF-8
user.classpath=C:/Users/maxma/Documents/GitHub/repo-gotowe/2026-04-27_20-41-46.025849;C:/Users/maxma/Documents/GitHub/repo-gotowe/2026-04-27_20-41-46.025849
