jmeter.save.saveservice.autoflush=true
jmeter.save.saveservice.connect_time=true
jmeterengine.force.system.exit=true
summariser.name=
jmeterengine.nongui.port=4446
jmeterengine.nongui.maxport=4446
jmeter.save.saveservice.timestamp_format=ms
sampleresult.default.encoding=UTF-8
user.classpath=C:/Users/maxma/Desktop/1/2026-02-12_02-28-00.691882;C:/Users/maxma/Desktop/1/2026-02-12_02-28-00.691882
